name: Test

on:
  workflow_run:
    workflows: ["Deploy Site"]
    types:
      - completed
      
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Update Post') }}
    steps:
    - run: echo ${{ github.event.head_commit.message }}
    - run: echo ${{ contains(github.event.head_commit.message, 'Update Post') }}
