name: Test

on:
  workflow_run:
    workflows: ["Deploy Site"]
    types:
      - completed
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.commits[0].message }}
    - run: echo ${{ contains(github.event.commits[0].message, 'Update Post') }}
